import React, { useState } from "react";
import {
  FileText, AlertCircle, CheckCircle, Star, Layout,
  Copy, Download
} from "lucide-react";
import { Users, Briefcase, GraduationCap, Wrench, Award, Cpu } from "lucide-react";

function AnalysisTabs({
  activeTab,
  setActiveTab,
  resumeData = {},
  downloadResumeText
}) {
  const [copied, setCopied] = useState(false);

  // ✅ CORRECT: Extract data from the RIGHT structure
  // Your resumeData comes from UploadResume with specific mapping
  const safeData = {
    // Use the props passed from UploadResume
    suggestions: resumeData.suggestions || [],
    strengths: resumeData.strengths || [],
    missingKeywords: resumeData.missingKeywords || [],
    analysis: resumeData.analysis || "No analysis available yet.",
    contactInfo: resumeData.contactInfo || {}
  };

  console.log("📋 AnalysisTabs received data:", {
    suggestionsCount: safeData.suggestions.length,
    strengthsCount: safeData.strengths.length,
    missingKeywordsCount: safeData.missingKeywords.length,
    analysisLength: safeData.analysis.length,
    contactInfo: safeData.contactInfo
  });

  const tabs = [
    { id: "analysis", label: "Summary", icon: FileText },
    { id: "suggestions", label: "Suggestions", icon: AlertCircle, count: safeData.suggestions.length },
    { id: "strengths", label: "Strengths", icon: CheckCircle, count: safeData.strengths.length },
    { id: "keywords", label: "Areas to Improve", icon: Star, count: safeData.missingKeywords.length },
    { id: "sections", label: "Sections", icon: Layout }
  ];

  const copyToClipboard = () => {
    navigator.clipboard.writeText(safeData.analysis);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Better section detection - checks actual analysis text
  const sections = [
    { name: "Contact Information", icon: Users, found: /email|phone|contact|@|\.com|\.in/i.test(safeData.analysis) },
    { name: "Professional Summary", icon: FileText, found: /summary|profile|objective|about/i.test(safeData.analysis) },
    { name: "Work Experience", icon: Briefcase, found: /experience|work|employment|internship|job/i.test(safeData.analysis) },
    { name: "Education", icon: GraduationCap, found: /education|degree|university|college|school|bachelor|master/i.test(safeData.analysis) },
    { name: "Skills", icon: Wrench, found: /skill|technical|proficiency|programming|framework|language/i.test(safeData.analysis) },
    { name: "Projects", icon: Cpu, found: /project|portfolio|github|repository|developed|built/i.test(safeData.analysis) },
    { name: "Achievements", icon: Award, found: /achievement|award|certification|certified|honor/i.test(safeData.analysis) }
  ];

  return (
    <div className="bg-white rounded-2xl shadow-xl overflow-hidden border border-gray-200">
      {/* TABS HEADER */}
      <div className="bg-gradient-to-r from-gray-50 to-white border-b border-gray-200 px-6">
        <div className="flex overflow-x-auto py-2">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center px-4 py-3 font-medium text-sm whitespace-nowrap transition-all duration-300 rounded-lg mx-1 ${
                activeTab === tab.id
                  ? "bg-gradient-to-r from-blue-500 to-purple-500 text-white shadow-md"
                  : "text-gray-600 hover:text-gray-900 hover:bg-gray-100"
              }`}
            >
              <tab.icon className="w-4 h-4 mr-2" />
              {tab.label}
              {tab.count > 0 && (
                <span className={`ml-2 px-2 py-0.5 text-xs rounded-full ${
                  activeTab === tab.id 
                    ? "bg-white text-blue-600" 
                    : "bg-gray-200 text-gray-700"
                }`}>
                  {tab.count}
                </span>
              )}
            </button>
          ))}
        </div>
      </div>

      <div className="p-6">
        
        {/* TAB 1 — SUMMARY */}
        {activeTab === "analysis" && (
          <div>
            <div className="flex justify-between items-center mb-6">
              <div>
                <h3 className="text-lg font-semibold text-gray-900">
                  AI Analysis Summary
                </h3>
                <p className="text-sm text-gray-500 mt-1">
                  Summary generated by Gemini AI based on your resume
                </p>
              </div>

              <div className="flex items-center space-x-3">
                <button
                  onClick={copyToClipboard}
                  className="flex items-center px-3 py-2 text-sm bg-blue-50 hover:bg-blue-100 text-blue-700 rounded-lg transition-colors duration-300"
                >
                  <Copy className="w-4 h-4 mr-2" />
                  {copied ? "Copied!" : "Copy Text"}
                </button>

                <button
                  onClick={downloadResumeText}
                  className="flex items-center px-3 py-2 text-sm bg-green-50 hover:bg-green-100 text-green-700 rounded-lg transition-colors duration-300"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download JSON
                </button>
              </div>
            </div>

            {/* SUMMARY CONTENT */}
            <div className="mt-4 p-4 bg-gray-50 rounded-xl border border-gray-200">
              <p className="text-gray-700 whitespace-pre-line">
                {safeData.analysis}
              </p>
            </div>

            {/* TEXT COUNTS */}
            <div className="mt-4 text-sm text-gray-500 flex items-center">
              <FileText className="w-4 h-4 mr-2" />
              <span>{safeData.analysis.length} characters</span>
              <span className="mx-2">•</span>
              <span>{safeData.analysis.split(/\s+/).length} words</span>
            </div>
          </div>
        )}

        {/* TAB 2 — SUGGESTIONS */}
        {activeTab === "suggestions" && (
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-6">
              Recommendations for Improvement ({safeData.suggestions.length})
            </h3>

            {safeData.suggestions.length > 0 ? (
              safeData.suggestions.map((suggestion, i) => (
                <div
                  key={i}
                  className="flex items-start p-4 bg-yellow-50 border border-yellow-200 rounded-xl mb-3"
                >
                  <AlertCircle className="w-5 h-5 text-yellow-700 mr-3 flex-shrink-0 mt-0.5" />
                  <p className="text-gray-700">{suggestion}</p>
                </div>
              ))
            ) : (
              <div className="text-center py-8 text-gray-500">
                <AlertCircle className="w-12 h-12 mx-auto text-gray-300 mb-3" />
                <p>No suggestions available. Try analyzing a different resume.</p>
              </div>
            )}
          </div>
        )}

        {/* TAB 3 — STRENGTHS */}
        {activeTab === "strengths" && (
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-6">
              Resume Strengths ({safeData.strengths.length})
            </h3>

            {safeData.strengths.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {safeData.strengths.map((strength, i) => (
                  <div
                    key={i}
                    className="flex items-start p-4 bg-green-50 border border-green-200 rounded-xl"
                  >
                    <CheckCircle className="w-5 h-5 text-green-700 mr-3 flex-shrink-0 mt-0.5" />
                    <p className="text-gray-700">{strength}</p>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-8 text-gray-500">
                <CheckCircle className="w-12 h-12 mx-auto text-gray-300 mb-3" />
                <p>No strengths detected in this resume.</p>
              </div>
            )}
          </div>
        )}

        {/* TAB 4 — AREAS TO IMPROVE */}
        {activeTab === "keywords" && (
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-6">
              Areas to Improve ({safeData.missingKeywords.length})
            </h3>

            {safeData.missingKeywords.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {safeData.missingKeywords.map((keyword, i) => (
                  <div
                    key={i}
                    className="flex items-center p-4 bg-red-50 border border-red-200 rounded-xl"
                  >
                    <Star className="w-5 h-5 text-red-600 mr-3" />
                    <span className="text-gray-700">{keyword}</span>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-8 text-green-500">
                <CheckCircle className="w-12 h-12 mx-auto text-green-300 mb-3" />
                <p className="font-medium">Great! No major areas need improvement.</p>
              </div>
            )}
          </div>
        )}

        {/* TAB 5 — SECTIONS */}
        {activeTab === "sections" && (
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-6">
              Resume Sections Detected
            </h3>
            <p className="text-gray-600 mb-6 text-sm">
              Based on analysis of: "{safeData.analysis.substring(0, 100)}..."
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {sections.map((section, i) => (
                <div
                  key={i}
                  className={`flex items-center p-4 rounded-xl border ${
                    section.found
                      ? "bg-green-50 border-green-300"
                      : "bg-gray-50 border-gray-200"
                  }`}
                >
                  <section.icon className={`w-5 h-5 mr-3 ${
                    section.found ? "text-green-600" : "text-gray-400"
                  }`} />
                  <div>
                    <p className={`font-medium ${
                      section.found ? "text-gray-900" : "text-gray-500"
                    }`}>
                      {section.name}
                    </p>
                    <p className={`text-sm ${
                      section.found ? "text-green-600" : "text-gray-400"
                    }`}>
                      {section.found ? "✓ Detected in text" : "✗ Not detected"}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

      </div>
    </div>
  );
}

export default AnalysisTabs;